name: Java CI with Gradle

on:
  push:
    branches:
      - 1.18.1-port
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17
          cache: "gradle"

      - name: Build
        run: ./gradlew build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/libs
